### ISSUE TITLE
Do I need to be logged in for BTC orders to match?

### ISSUE THREAD

**Issue by dbolser** [loon3/btcpaymarket#1]
This was airways the problem with counterwallet.

**Comment by loon3** [comment]
The order will match, but it will be in pending status until you submit the order match transaction which completes the order.  You have about 3 hours to submit it after your order matches (20 blocks).

From the readme...

> Buying assets with BTC requires two transactions. First, click on an Active Order in the Asset Market table (highlighted in yellow) to send an Order transaction. After the Order transaction has confirmed, a Pending Order Match will appear in the Order Matches table. Click on the Pending Order Match to send an Order Match transaction (BTCPAY) to complete your order.

**Comment by dbolser** [comment]
Typically how long do you have to wait before the order matches?

**Comment by loon3** [comment]
The order will match as soon as your buy order is included in a block, so one confirmation

**Comment by dbolser** [comment]
Ta
